# .streamlit/secrets.toml

# Don't use this for deployment, use remote server
[connections.postgresql]
dialect = "postgresql"
host = "localhost"
port = 5432
database = "records_db"
username = "postgres"
password = "1234"
